import JSZip from 'jszip';
import { IconStyle, VectorXmlOptions, AndroidSnippets } from '../types';

// In-memory cache for fetched SVGs to avoid redundant network requests
const svgCache = new Map<string, string>();

/**
 * Returns the Google Fonts CDN URL for the SVG of a Material Symbol
 */
export function getGoogleIconSvgUrl(
  name: string,
  style: IconStyle = 'outlined',
  isFilled: boolean = false
): string {
  const styleName = `materialsymbols${style}`;
  const fillPath = isFilled ? 'fill1' : 'default';
  return `https://fonts.gstatic.com/s/i/short-term/release/${styleName}/${name}/${fillPath}/24px.svg`;
}

/**
 * Fetches the SVG content for a given icon and style
 */
export async function fetchIconSvg(
  name: string,
  style: IconStyle = 'outlined',
  isFilled: boolean = false
): Promise<string> {
  const cacheKey = `${name}_${style}_${isFilled ? '1' : '0'}`;
  if (svgCache.has(cacheKey)) {
    return svgCache.get(cacheKey)!;
  }

  const url = getGoogleIconSvgUrl(name, style, isFilled);
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch SVG for icon "${name}" (${response.status})`);
  }

  const svgText = await response.text();
  svgCache.set(cacheKey, svgText);
  return svgText;
}

/**
 * Sanitizes an icon name to a valid Android drawable resource name
 * Android resources must match [a-z0-9_]+ and start with a letter.
 */
export function getAndroidDrawableName(iconName: string): string {
  const clean = iconName.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  return clean.startsWith('ic_') ? clean : `ic_${clean}`;
}

export interface ParsedSvg {
  viewBox: string;
  minX: number;
  minY: number;
  width: number;
  height: number;
  paths: string[];
}

/**
 * Parses SVG text into pathData and viewBox coordinates
 */
export function parseSvg(svgText: string): ParsedSvg {
  const viewBoxMatch = svgText.match(/viewBox=["']([^"']+)["']/i);
  let minX = 0;
  let minY = -960;
  let width = 960;
  let height = 960;
  let viewBoxStr = '0 -960 960 960';

  if (viewBoxMatch && viewBoxMatch[1]) {
    viewBoxStr = viewBoxMatch[1].trim();
    const parts = viewBoxStr.split(/[\s,]+/).map(Number);
    if (parts.length === 4 && !parts.some(isNaN)) {
      minX = parts[0];
      minY = parts[1];
      width = parts[2];
      height = parts[3];
    }
  }

  // Extract path data using regex
  const pathMatches = svgText.matchAll(/<path[^>]*\bd=["']([^"']+)["']/gi);
  const paths: string[] = [];
  for (const match of pathMatches) {
    if (match[1] && match[1].trim()) {
      paths.push(match[1].trim());
    }
  }

  return {
    viewBox: viewBoxStr,
    minX,
    minY,
    width,
    height,
    paths,
  };
}

/**
 * Generates Android Vector Drawable XML string
 */
export function generateVectorXml(
  iconName: string,
  svgText: string,
  options: VectorXmlOptions
): string {
  const parsed = parseSvg(svgText);
  const paths = parsed.paths;

  const widthDp = options.widthDp || 24;
  const heightDp = options.heightDp || 24;
  const fillColor = options.fillColor || '#FF000000';
  const tintAttr = options.tint ? `\n    android:tint="${options.tint}"` : '';
  const alphaAttr = options.alpha !== undefined && options.alpha < 1 ? `\n    android:alpha="${options.alpha.toFixed(2)}"` : '';

  const viewportWidth = parsed.width || 960;
  const viewportHeight = parsed.height || 960;
  const needsTranslate = parsed.minY !== 0 || parsed.minX !== 0;
  const translateY = -parsed.minY;
  const translateX = -parsed.minX;

  // Build the XML paths
  let bodyContent = '';

  if (needsTranslate) {
    const translateAttrs = [
      translateX !== 0 ? `android:translateX="${translateX}"` : '',
      translateY !== 0 ? `android:translateY="${translateY}"` : '',
    ].filter(Boolean).join(' ');

    const innerPaths = paths
      .map(
        (p) => `        <path
            android:fillColor="${fillColor}"
            android:pathData="${p}" />`
      )
      .join('\n');

    bodyContent = `    <group ${translateAttrs}>
${innerPaths}
    </group>`;
  } else {
    bodyContent = paths
      .map(
        (p) => `    <path
        android:fillColor="${fillColor}"
        android:pathData="${p}" />`
      )
      .join('\n');
  }

  return `<!--
  Google Material Symbol: ${iconName}
  Style: ${options.style} | Fill: ${options.isFilled ? '1' : '0'}
  Generated by Google Icons to Vector XML Tool
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${widthDp}dp"
    android:height="${heightDp}dp"
    android:viewportWidth="${viewportWidth}"
    android:viewportHeight="${viewportHeight}"${tintAttr}${alphaAttr}>
${bodyContent}
</vector>`.trim();
}

/**
 * Generates Android XML & Jetpack Compose code snippets
 */
export function getAndroidSnippets(iconName: string, options: VectorXmlOptions): AndroidSnippets {
  const resName = getAndroidDrawableName(iconName);
  const widthDp = options.widthDp || 24;
  const heightDp = options.heightDp || 24;

  const xmlLayout = `<!-- XML Layout -->
<ImageView
    android:layout_width="${widthDp}dp"
    android:layout_height="${heightDp}dp"
    android:src="@drawable/${resName}"
    android:contentDescription="${iconName}" />`;

  const jetpackCompose = `// Jetpack Compose
Icon(
    painter = painterResource(id = R.drawable.${resName}),
    contentDescription = "${iconName}",
    modifier = Modifier.size(${widthDp}.dp)
)`;

  return {
    xmlLayout,
    jetpackCompose,
    resourceFileName: `${resName}.xml`,
  };
}

/**
 * Downloads text as a file in the browser
 */
export function triggerFileDownload(content: string, filename: string, mimeType: string = 'application/xml') {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Downloads multiple icons as a ZIP file
 */
export async function downloadBatchAsZip(
  icons: Array<{ name: string; svgText: string }>,
  options: VectorXmlOptions,
  onProgress?: (current: number, total: number) => void
): Promise<void> {
  const zip = new JSZip();
  const folder = zip.folder('drawable') || zip;

  for (let i = 0; i < icons.length; i++) {
    const item = icons[i];
    const xml = generateVectorXml(item.name, item.svgText, options);
    const fileName = `${getAndroidDrawableName(item.name)}.xml`;
    folder.file(fileName, xml);
    if (onProgress) {
      onProgress(i + 1, icons.length);
    }
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `google_icons_vector_xml_${options.style}.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
